import type { Metadata } from 'next';
import { Inter as FontSans, KoHo } from 'next/font/google';
import { cn } from '@/lib/utils';
import './globals.css';
import NavBar from '@/components/NavBar';

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

const fontKoho = KoHo({
  subsets: ['latin'],
  variable: '--font-koho',
  weight: ['500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Atc Dreamteam',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={cn(
          'h-screen bg-none container px-4 pb-4 font-sans antialiased flex flex-col md:px-6 md:pb-6',
          'bg-[linear-gradient(to_bottom,rgba(0,0,0,0.8),rgba(0,0,0,0)),url("/assets/image/arena_4.webp")]',
          fontSans.variable,
          fontKoho.variable
        )}
        style={{
          backgroundPosition: 'center',
        }}
      >
        <NavBar />
        {children}
      </body>
    </html>
  );
}
